#' The order of output files generated by this script DOES NOT necessarily 
#' reflect the order in which the figures appear in the manuscript. To find the 
#' output associated with a specific figure of table from the manuscript use 
#' hints from the comments (e.g. `HINT: Figure 2 in the manuscript`). 
#' Please note, that some results generated by this script are not outlined in 
#' the main body of the manuscript.

# Plots (between studies)

if (!dir.exists("./output")) {dir.create("./output")}

odir = "./output/plots-and-stats"
if (!dir.exists(odir)) {dir.create(odir)}

osubdir = file.path(odir, paste0(
  "studies-", paste(studies, collapse = "-"),
  "-required-", as.character(required)))
if (!dir.exists(osubdir)) {dir.create(osubdir)}

fdir.create = function(name) {
  fdir = file.path(osubdir, name)
  if (!dir.exists(fdir)) {dir.create(fdir)}
  fdir
}

## Plot comparison of mean ratings between studies

fdir = fdir.create("Comparison of story ratings between studies")

df = story_mean_ratings_study %>%
  pivot_wider(id_cols = c("ord","code","category","part"),
              names_from = "study",
              names_sep = ".",
              names_sort = T,
              values_from = c("mean","n"))

plot.me1 = function(data) {
  ggplot(data, aes(`mean.Study 1`, `mean.Study 2`, label = code, colour=category)) +
    geom_point() +
    xlim(c(-1,100)) + ylim(c(-1,100)) +
    xlab("Mean ratings in Study 1 in Poland (convenience sampling)") + ylab("Mean ratings in Study 2 in Poland (purposive sampling)") +
    scale_color_manual(values = colors_categories, name = "Story type") +
    geom_abline(aes(intercept = 0, slope = 1)) +
    #geom_label(data = subset(data, abs(`mean.Study 1` - `mean.Study 2`) > 25), show.legend = FALSE) +
    beauty
}

plot.me2 = function(data) {
  ggplot(data, aes(`mean.Study 2`, `mean.Study 3`, label = code, colour=category)) +
    geom_point() +
    xlim(c(-1,100)) + ylim(c(-1,100)) +
    xlab("Mean ratings in Study 2 in Poland (purposive sampling)") + ylab("Mean ratings in Study 3 in Norway (purposive sampling)") +
    scale_color_manual(values = colors_categories, name = "Story type") +
    geom_abline(aes(intercept = 0, slope = 1)) +
    #geom_label(data = subset(data, abs(`mean.Study 2` - `mean.Study 3`) > 25), show.legend = FALSE) +
    beauty
}

### Separate plots
for (i in 0:6) {
  subdf = filter(df, part == i)
  p = plot.me1(subdf) +
    labs(title = paste("Differences in mean ratings of stories on", tolower(labels_scales[i+1]) , "scale"))
  ggsave(paste0("Study 1 vs Study 2 - ",part_to_scale[i+1], ".png"), p, path = fdir)
}

for (i in 0:6) {
  subdf = filter(df, part == i)
  p = plot.me2(subdf) +
    labs(title = paste("Differences in mean ratings of stories on", tolower(labels_scales[i+1]) , "scale"))
  ggsave(paste0("Study 2 vs Study 3 - ",part_to_scale[i+1], ".png"), p, path = fdir)
}

### Wrapped plots
p = plot.me1(df) +
  facet_wrap(~part, ncol = 2, labeller = as_labeller(part_to_scale)) + 
  labs(title = "Differences in mean ratings of stories on each scale") +
  theme(plot.title = element_text(size=22),
        strip.text.x = element_text(size = 14),
        axis.title = element_text(size=14),
        axis.text = element_text(size=12),
        legend.title = element_text(size=12),
        legend.text = element_text(size=12))
ggsave("Comparison of story ratings between Study 1 and Study 2 - Facet by scale.png", p, width = 10, height = 15, path = osubdir) # HINT: Figure S1 in the manuscript

p = plot.me2(df) +
  facet_wrap(~part, ncol = 2, labeller = as_labeller(part_to_scale)) + 
  labs(title = "Differences in mean ratings of stories on each scale") +
  theme(plot.title = element_text(size=22),
        strip.text.x = element_text(size = 14),
        axis.title = element_text(size=14),
        axis.text = element_text(size=12),
        legend.title = element_text(size=12),
        legend.text = element_text(size=12))
ggsave("Comparison of story ratings between Study 2 and Study 3 - Facet by scale.png", p, width = 10, height = 15, path = osubdir) # HINT: Figure S2 in the manuscript
